In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

In [2]:
df= pd.read_table('./Pre_processed_data/merged_dataframe_shopping.csv', delimiter= ',', encoding='euc-kr')

KeyboardInterrupt:

In [ ]:
df.head()

In [4]:
df.drop('Unnamed: 0', axis= 1, inplace= True)

In [5]:
df.PD_M_NM.nunique()

690

In [6]:
df.PD_S_NM.nunique()

3148

In [7]:
df.PD_H_NM.nunique()

148

In [8]:
df['YEARMONTH']= 100*df['YEAR']+df['MONTH']

In [9]:
df['DAYHOUR']= 100*df['DAY']+ df['HOUR']

In [10]:
df.drop(['YEAR', 'MONTH', 'DAY', 'HOUR'], axis= 1, inplace= True)

In [11]:
df= pd.get_dummies(df, columns= ['BIZ_UNIT'])

In [12]:
agg_func= {'RCT_NO': 'count', 'PD_S_C': lambda x: x.nunique(), 'DAYHOUR': lambda x: x.nunique(), 'BUY_AM': 'sum', 'BIZ_UNIT_A01': 'sum', 'BIZ_UNIT_A02': 'sum', 'BIZ_UNIT_A03': 'sum', 'BIZ_UNIT_A04': 'sum', 'BIZ_UNIT_A05': 'sum',}

In [13]:
df_restructured= df.groupby(['ID', 'YEARMONTH']).agg(agg_func)

In [17]:
df_restructured

                 RCT_NO  PD_S_C  DAYHOUR  BUY_AM  BIZ_UNIT_A01  BIZ_UNIT_A02  \
ID    YEARMONTH
1     201501          4       4        2  105800           4.0           0.0
      201503          4       4        2  733900           4.0           0.0
      201504          1       1        1   13000           1.0           0.0
      201505         12       9        4  434230          11.0           1.0
      201506          9       6        4  579000           9.0           0.0
      201508          8       6        4  700000           8.0           0.0
      201510          1       1        1   32000           1.0           0.0
      201511         10       8        4  870950          10.0           0.0
      201512          6       5        3  227050           6.0           0.0
2     201412          6       6        1   17550           0.0           6.0
      201501         22      15        7  274722           8.0          14.0
      201502         27      21        4  160700           0.0          27.0
      201503         23      15        4  120140           0.0          23.0
      201504          1       1        1   15000           0.0           1.0
      201505         14      10        3  128570           0.0          14.0
      201506         24      19        5  186860           0.0          24.0
      201507         51      33        8  326090           0.0          51.0
      201508          9       9        4  135800           0.0           9.0
      201509         22      14        5  279860           0.0          22.0
      201510         35      26        4  206110           0.0          35.0
      201511         12      10        3   69100           0.0          12.0
      201512         13       8        2   58640           0.0          13.0
3     201501          8       7        5  354900           4.0           4.0
      201502         10       9        2  114500           1.0           9.0
      201503         12       9        2   91635           1.0          11.0
      201504         13      10        2   79470           0.0          13.0
      201505          3       2        2   78900           3.0           0.0
      201508          5       3        2  227000           3.0           0.0
      201509         16      13        1  117309           0.0          16.0
      201510          8       4        4  492800           8.0           0.0
...                 ...     ...      ...     ...           ...           ...
19966 201510          4       4        1   23860           0.0           4.0
19968 201510         16       8        5   62970           0.0           0.0
      201511         16      10        4   85472           0.0           0.0
      201512         16      10        4   71905           0.0           0.0
19970 201512         28      10        2  968200           0.0          28.0
19973 201511          1       1        1   99000           1.0           0.0
      201512          2       2        2  263200           2.0           0.0
19974 201510         14       7        2  105360           0.0           4.0
      201511          6       3        1   19520           0.0           0.0
      201512         64      30        3  324386           0.0          64.0
19975 201512          3       1        2  898000           3.0           0.0
19978 201511          2       1        1  358000           2.0           0.0
      201512          7       5        1  246400           0.0           7.0
19979 201512          3       3        2  147800           3.0           0.0
19981 201511          5       2        2   39680           2.0           3.0
      201512          4       4        1  207000           4.0           0.0
19982 201512          1       1        1   45000           0.0           1.0
19983 201511          2       2        1    4930           0.0           2.0
19984 201512          1       1        1   10000           0.0           1.0
19985 201512         13      11        3   91620           0.0          13.0
19987 201512          4       4        2   20510           0.0           2.0
19988 201511          2       2        1   34800           0.0           2.0
19989 201512          1       1        1    2590           0.0           0.0
19992 201512          2       2        2   24000           1.0           1.0
19995 201512          1       1        1   79800           1.0           0.0
19996 201512         27      25        1  272500           0.0          27.0
19997 201512         44      16        2  136368           0.0           0.0
19998 201512          9       7        2  143700           0.0           9.0
19999 201512          1       1        1  179000           1.0           0.0
20000 201512          1       1        1   69000           1.0           0.0

                 BIZ_UNIT_A03  BIZ_UNIT_A04  BIZ_UNIT_A05
ID    YEARMONTH
1     201501              0.0           0.0             0
      201503              0.0           0.0             0
      201504              0.0           0.0             0
      201505              0.0           0.0             0
      201506              0.0           0.0             0
      201508              0.0           0.0             0
      201510              0.0           0.0             0
      201511              0.0           0.0             0
      201512              0.0           0.0             0
2     201412              0.0           0.0             0
      201501              0.0           0.0             0
      201502              0.0           0.0             0
      201503              0.0           0.0             0
      201504              0.0           0.0             0
      201505              0.0           0.0             0
      201506              0.0           0.0             0
      201507              0.0           0.0             0
      201508              0.0           0.0             0
      201509              0.0           0.0             0
      201510              0.0           0.0             0
      201511              0.0           0.0             0
      201512              0.0           0.0             0
3     201501              0.0           0.0             0
      201502              0.0           0.0             0
      201503              0.0           0.0             0
      201504              0.0           0.0             0
      201505              0.0           0.0             0
      201508              2.0           0.0             0
      201509              0.0           0.0             0
      201510              0.0           0.0             0
...                       ...           ...           ...
19966 201510              0.0           0.0             0
19968 201510             16.0           0.0             0
      201511             16.0           0.0             0
      201512             16.0           0.0             0
19970 201512              0.0           0.0             0
19973 201511              0.0           0.0             0
      201512              0.0           0.0             0
19974 201510             10.0           0.0             0
      201511              6.0           0.0             0
      201512              0.0           0.0             0
19975 201512              0.0           0.0             0
19978 201511              0.0           0.0             0
      201512              0.0           0.0             0
19979 201512              0.0           0.0             0
19981 201511              0.0           0.0             0
      201512              0.0           0.0             0
19982 201512              0.0           0.0             0
19983 201511              0.0           0.0             0
19984 201512              0.0           0.0             0
19985 201512              0.0           0.0             0
19987 201512              2.0           0.0             0
19988 201511              0.0           0.0             0
19989 201512              1.0           0.0             0
19992 201512              0.0           0.0             0
19995 201512              0.0           0.0             0
19996 201512              0.0           0.0             0
19997 201512             44.0           0.0             0
19998 201512              0.0           0.0             0
19999 201512              0.0           0.0             0
20000 201512              0.0           0.0             0

[156620 rows x 9 columns]

In [15]:
df.loc[df['ID']== 1].sort_values(['YEARMONTH', 'DAYHOUR'])

,ID,RCT_NO,PD_S_C,BR_C,BUY_AM,BUY_CT,AGE_PRD,HOM_PST_NO,PD_S_NM,PD_M_NM,...,IS_FEMALE,PRVIN,DESTRICT,YEARMONTH,DAYHOUR,BIZ_UNIT_A01,BIZ_UNIT_A02,BIZ_UNIT_A03,BIZ_UNIT_A04,BIZ_UNIT_A05
554136,1,100812,236,2,29800,1,60,052,홈웨어,기타의류,...,0,서울특별시,강동구,201501,2812,1,0,0,0,0
1128450,1,157750,121,2,18000,2,60,052,식당가 한식,가공식품,...,0,서울특별시,강동구,201501,2813,1,0,0,0,0
1257722,1,37450,367,2,48000,1,60,052,L/C골프의류,골프용품,...,0,서울특별시,강동구,201501,2813,1,0,0,0,0
3765247,1,110941,34,2,10000,1,60,052,기타생선,수산품,...,0,서울특별시,강동구,201501,2813,1,0,0,0,0
1230435,1,191488,479,2,169000,1,60,052,주방잡화,주방용품,...,0,서울특별시,강동구,201503,712,1,0,0,0,0
1525024,1,222915,2,2,9000,1,60,052,돈육,육류,...,0,서울특별시,강동구,201503,712,1,0,0,0,0
2549132,1,149128,15,2,8900,1,60,052,디저트류,차/커피,...,0,서울특별시,강동구,201503,712,1,0,0,0,0
2354121,1,129205,493,2,547000,1,60,052,기능성침대,생활잡화,...,0,서울특별시,강동구,201503,811,1,0,0,0,0
2633538,1,325566,46,2,13000,1,60,052,초밥,가공식품,...,0,서울특별시,강동구,201504,215,1,0,0,0,0
425501,1,204739,71,2,1000,2,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201505,1312,1,0,0,0,0
425502,1,204739,71,2,6900,1,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201505,1312,1,0,0,0,0
425503,1,204739,71,2,2400,2,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201505,1312,1,0,0,0,0
425504,1,204739,71,2,1000,1,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201505,1312,1,0,0,0,0
1812884,1,35656,1287,7,72000,1,60,052,홍삼선물세트,건강선물세트,...,0,서울특별시,강동구,201505,1312,0,1,0,0,0
2775191,1,19373,448,2,42400,1,60,052,내의,아동,...,0,서울특별시,강동구,201505,1313,1,0,0,0,0
3173189,1,235737,232,2,114000,1,60,052,란제리,란제리/내의,...,0,서울특별시,강동구,201505,1313,1,0,0,0,0
149361,1,314285,478,2,15000,1,60,052,수입주방,주방용품,...,0,서울특별시,강동구,201505,1314,1,0,0,0,0
2214351,1,193826,123,2,44000,2,60,052,식당가 일식,가공식품,...,0,서울특별시,강동구,201505,1314,1,0,0,0,0
2007855,1,378813,1,2,24530,1,60,052,우육,육류,...,0,서울특별시,강동구,201505,1315,1,0,0,0,0
2671449,1,427005,18,2,10000,1,60,052,청과,농산물,...,0,서울특별시,강동구,201505,1315,1,0,0,0,0
3780073,1,160871,318,2,101000,1,60,052,L/C 아웃도어,스포츠,...,0,서울특별시,강동구,201505,1315,1,0,0,0,0
3491178,1,350915,499,2,51200,1,60,052,수입도자기,식기,...,0,서울특별시,강동구,201506,1017,1,0,0,0,0
3220135,1,208990,366,2,192000,1,60,052,N/B골프의류,골프용품,...,0,서울특별시,강동구,201506,1018,1,0,0,0,0
3501793,1,198210,366,2,192000,1,60,052,N/B골프의류,골프용품,...,0,서울특별시,강동구,201506,1018,1,0,0,0,0
653255,1,181719,53,2,5000,1,60,052,"제과,제빵",가공식품,...,0,서울특별시,강동구,201506,1019,1,0,0,0,0
1909645,1,421735,71,2,1000,2,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201506,1019,1,0,0,0,0
1909646,1,421735,71,2,10000,1,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201506,1019,1,0,0,0,0
1909647,1,421735,71,2,4800,4,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201506,1019,1,0,0,0,0
2301053,1,364056,16,2,13000,1,60,052,에스닉푸드,가공식품,...,0,서울특별시,강동구,201506,1019,1,0,0,0,0
993424,1,132922,462,2,110000,1,60,052,수입청소기 외,소형가전,...,0,서울특별시,강동구,201506,1311,1,0,0,0,0
3527585,1,234024,191,2,224000,1,60,052,수입화,트래디셔널,...,0,서울특별시,강동구,201508,118,1,0,0,0,0
422865,1,48978,366,2,166400,1,60,052,N/B골프의류,골프용품,...,0,서울특별시,강동구,201508,119,1,0,0,0,0
1627606,1,343631,367,2,89000,1,60,052,L/C골프의류,골프용품,...,0,서울특별시,강동구,201508,119,1,0,0,0,0
2825720,1,441391,15,2,3200,1,60,052,디저트류,차/커피,...,0,서울특별시,강동구,201508,119,1,0,0,0,0
3483645,1,293250,366,2,166600,1,60,052,N/B골프의류,골프용품,...,0,서울특별시,강동구,201508,518,1,0,0,0,0
2274382,1,443974,71,2,4800,4,60,052,어묵,젓갈/반찬,...,0,서울특별시,강동구,201508,519,1,0,0,0,0
3205908,1,423380,46,2,23000,1,60,052,초밥,가공식품,...,0,서울특별시,강동구,201508,519,1,0,0,0,0
3704979,1,423993,46,2,23000,1,60,052,초밥,가공식품,...,0,서울특별시,강동구,201508,519,1,0,0,0,0
2354120,1,129205,446,1,32000,1,60,052,유아복,아동,...,0,서울특별시,강동구,201510,2415,1,0,0,0,0
3666679,1,321854,353,2,496200,1,60,052,몬츄라,스포츠,...,0,서울특별시,강동구,201511,417,1,0,0,0,0
433811,1,370752,15,2,3200,1,60,052,디저트류,차/커피,...,0,서울특별시,강동구,201511,418,1,0,0,0,0
2676908,1,444192,77,2,990,1,60,052,음료,주류,...,0,서울특별시,강동구,201511,418,1,0,0,0,0
2676909,1,444192,20,2,3000,1,60,052,유기농채소,농산물,...,0,서울특별시,강동구,201511,418,1,0,0,0,0
3442855,1,331614,294,2,60000,2,60,052,셔츠단기행사,셔츠,...,0,서울특별시,강동구,201511,418,1,0,0,0,0
3660494,1,304616,20,2,3560,1,60,052,유기농채소,농산물,...,0,서울특별시,강동구,201511,418,1,0,0,0,0
993425,1,132922,446,2,29000,1,60,052,유아복,아동,...,0,서울특별시,강동구,201511,2115,1,0,0,0,0
993426,1,132922,446,2,47000,1,60,052,유아복,아동,...,0,서울특별시,강동구,201511,2115,1,0,0,0,0
3426736,1,242470,122,2,24000,3,60,052,식당가 중식,가공식품,...,0,서울특별시,강동구,201511,2115,1,0,0,0,0
1774882,1,368976,340,2,204000,1,60,052,디스커버리,스포츠,...,0,서울특별시,강동구,201511,2116,1,0,0,0,0
59668,1,383515,478,2,28000,1,60,052,수입주방,주방용품,...,0,서울특별시,강동구,201512,1617,1,0,0,0,0
1695769,1,211042,121,2,9000,1,60,052,식당가 한식,가공식품,...,0,서울특별시,강동구,201512,1617,1,0,0,0,0
1695770,1,211042,121,2,8500,1,60,052,식당가 한식,가공식품,...,0,서울특별시,강동구,201512,1617,1,0,0,0,0
3601935,1,434224,82,2,9000,1,60,052,수입식품,차/커피,...,0,서울특별시,강동구,201512,1618,1,0,0,0,0
3601936,1,434224,3,2,6550,1,60,052,계육,육류,...,0,서울특별시,강동구,201512,1618,1,0,0,0,0
422866,1,48978,232,2,166000,1,60,052,란제리,란제리/내의,...,0,서울특별시,강동구,201512,2812,1,0,0,0,0

In [16]:
df_restructured.to_csv('./Pre_processed_data/groupby_ID_YEARMONTH.csv')